name: Haoma
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.2
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - backcall=0.2.0
  - biopython=1.78
  - blas=1.0
  - bleach=4.0.0
  - bottleneck=1.3.2
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - cffi=1.14.6
  - click=8.0.1
  - dbus=1.13.18
  - debugpy=1.4.1
  - decorator=5.0.9
  - defusedxml=0.7.1
  - entrypoints=0.3
  - expat=2.4.1
  - gettext=0.21.0
  - glib=2.69.1
  - greenlet=1.1.2
  - icu=58.2
  - importlib-metadata=4.8.1
  - importlib_metadata=4.8.1
  - intel-openmp=2021.3.0
  - ipykernel=6.2.0
  - ipython=7.27.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jedi=0.18.0
  - jinja2=3.0.1
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=7.0.1
  - jupyter_console=6.4.0
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - libcxx=12.0.0
  - libffi=3.3
  - libiconv=1.16
  - libpng=1.6.37
  - libsodium=1.0.18
  - libxml2=2.9.12
  - llvm-openmp=12.0.0
  - markupsafe=2.0.1
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - nbclient=0.5.3
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - notebook=6.4.3
  - numexpr=2.7.3
  - numpy=1.20.3
  - numpy-base=1.20.3
  - openssl=1.1.1l
  - packaging=21.0
  - pandas=1.3.2
  - pandocfilters=1.4.3
  - parso=0.8.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.2.2
  - pivottablejs=0.9.0
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.17
  - prompt_toolkit=3.0.17
  - ptyprocess=0.7.0
  - pycparser=2.20
  - pygments=2.10.0
  - pymysql=1.0.2
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - python=3.8.11
  - python-dateutil=2.8.2
  - python-dotenv=0.19.0
  - python_abi=3.8
  - pytz=2021.1
  - pyzmq=22.2.1
  - qt=5.9.7
  - qtconsole=5.1.0
  - qtpy=1.10.0
  - readline=8.1
  - send2trash=1.5.0
  - setuptools=58.0.4
  - sip=4.19.8
  - six=1.16.0
  - sqlalchemy=1.4.25
  - sqlite=3.36.0
  - terminado=0.9.4
  - testpath=0.5.0
  - tk=8.6.10
  - tornado=6.1
  - traitlets=5.0.5
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.0
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.5.0
  - zlib=1.2.11
  - pip:
    - entrezpy==2.1.3

